=== ipponsoft/MDA.no-m2t/src/metamodel/NakedObjectsMergeModel.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/NakedObjectsMarkup" elementFormDefault="qualified" targetNamespace="http://www.example.org/NakedObjectsMarkup">
	<complexType name="NOClassType">
		<sequence>
			<element maxOccurs="1" minOccurs="0" name="idField" type="string"/>
			<element maxOccurs="unbounded" minOccurs="0" name="nameField" type="string"/>
			<element maxOccurs="1" minOccurs="0" name="serviceEntryName" type="string"/>
			<element maxOccurs="1" minOccurs="0" name="title" type="string"/>
			<element maxOccurs="1" minOccurs="0" name="serviceIcon" type="string"/>
		</sequence>
		<attribute name="name" type="string"/>
	</complexType>
	<complexType name="NOClassListType">
		<sequence>
			<element maxOccurs="unbounded" minOccurs="0" name="NOClass" type="tns:NOClassType"/>
		</sequence>
	</complexType>
	<element name="NOClasses" type="tns:NOClassListType"/>
</schema>

=== ipponsoft/MDA.no-m2t/src/transformation/noMerge.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<tns:NOClasses xmlns:tns="http://www.example.org/NakedObjectsMarkup" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/NakedObjectsMarkup ../metamodel/NakedObjectsMergeModel.xsd ">
	<tns:NOClass name="Benutzer">
		<tns:idField>benutzerNummer</tns:idField>
		<tns:title>name + ", " + vorname</tns:title>
		<tns:serviceIcon>Person.png</tns:serviceIcon>
		<tns:serviceEntryName>Benutzer</tns:serviceEntryName>
	</tns:NOClass>
	<tns:NOClass name="CD">
		<tns:idField>medienNummer</tns:idField>
		<tns:serviceIcon>CD.png</tns:serviceIcon>
		<tns:serviceEntryName>CDs</tns:serviceEntryName>
	</tns:NOClass>
	<tns:NOClass name="Buch">
		<tns:idField>medienNummer</tns:idField>
		<tns:serviceIcon>Buch.gif</tns:serviceIcon>
		<tns:serviceEntryName>Bücher</tns:serviceEntryName>
	</tns:NOClass>
	<tns:NOClass name="Medium">
		<tns:idField>medienNummer</tns:idField>
		<tns:title>autor + ": " + titel</tns:title>
		<tns:serviceEntryName>Medien</tns:serviceEntryName>
	</tns:NOClass>
	<tns:NOClass name="Ausleihe">
		<tns:idField>nummer</tns:idField>
		<tns:title>leser.getName() + " -> " + medium.getAutor() + ": " + medium.getTitel()</tns:title>
		<tns:serviceIcon>Vorgang.gif</tns:serviceIcon>
		<tns:serviceEntryName>Vorgänge</tns:serviceEntryName>
	</tns:NOClass>
</tns:NOClasses>
